{
  "sksl": {
    "entrypoint": "bloom_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 iResolution;\nuniform shader image;\nuniform half2 image_size;\n\nvec4 fragColor;\n\nfloat Threshold;\nfloat Intensity;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec4 FLT_flutter_local_blend()\n{\n    vec2 fragCoord = FLT_flutter_local_FlutterFragCoord();\n    vec2 Coord = (fragCoord / iResolution) * vec2(1.0);\n    float MipBias = 4.0;\n    vec2 TexelSize = vec2(MipBias) / iResolution;\n    vec4 Color = image.eval(image_size * ( Coord));\n    for (float i = 1.0; i <= 6.0; i += 1.0)\n    {\n        float inv = 1.0 / i;\n        Color += image.eval(image_size * ( Coord + (vec2(TexelSize.x, TexelSize.y) * inv)));\n        Color += image.eval(image_size * ( Coord + (vec2(-TexelSize.x, TexelSize.y) * inv)));\n        Color += image.eval(image_size * ( Coord + (vec2(TexelSize.x, -TexelSize.y) * inv)));\n        Color += image.eval(image_size * ( Coord + (vec2(-TexelSize.x, -TexelSize.y) * inv)));\n    }\n    return Color / vec4(24.0);\n}\n\nvoid FLT_main()\n{\n    Threshold = 0.100000001490116119384765625;\n    Intensity = 0.4000000059604644775390625;\n    vec2 fragCoord_1 = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = (fragCoord_1 / iResolution) * vec2(1.0);\n    vec4 Color_1 = image.eval(image_size * ( uv));\n    vec4 Highlight = (clamp(FLT_flutter_local_blend() - vec4(Threshold), vec4(0.0), vec4(1.0)) * 1.0) / vec4(1.0 - Threshold);\n    fragColor = vec4(1.0) - ((vec4(1.0) - Color_1) * (vec4(1.0) - (Highlight * Intensity)));\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "image",
        "rows": 1,
        "type": 12
      }
    ]
  }
}