{
  "sksl": {
    "entrypoint": "void_background_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float iTime;\nuniform vec2 iResolution;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 w = FLT_flutter_local_FlutterFragCoord();\n    vec2 r = iResolution;\n    vec2 p = w - (r * 0.5);\n    float d = length(p) / r.y;\n    float c = 1.0;\n    float x = pow(d, 0.100000001490116119384765625);\n    float y = atan(p.x, p.y) / 6.280000209808349609375;\n    for (float i = 0.0; i < 3.0; i += 1.0)\n    {\n        c = min(c, length((fract(vec2(x - ((iTime * i) * 0.004999999888241291046142578125), fract(y + (i * 0.125)) * 0.5) * 20.0) * 2.0) - vec2(1.0)));\n    }\n    fragColor = vec4(vec3(d + ((((20.0 * c) * d) * d) * (0.60000002384185791015625 - d))), 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "iTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "iResolution",
        "rows": 2,
        "type": 10
      }
    ]
  }
}